# -*- coding: utf-8 -*-
"""
Автоматически сгенерированный словарь: КОД (переменная) -> оригинальное
название предмета (как оно выгружается из игры, без изменений).

Правила генерации кода:
  - Если название на латинице - используется как есть (только убраны
    пробелы, кавычки, апострофы и дефисы).
  - Если в названии есть кириллица - кириллическая часть транслитерирована
    (не переведена!) в латиницу, например "Дизель" -> "Dizel".
  - Суффикс "(Ящик)" (означающий, что предмет в ящике) в код и в это
    название НЕ включается - это тот же предмет, что и без ящика
    (аналогично отдельному полю "crated" в relay.py).

Проверьте коды перед использованием - для некоторых предметов транслит
мог получиться неоднозначным (спецсимволы, дефисы, дробные числа).
На следующем шаге сюда добавляется сопоставление с иконками.
"""

ITEM_CODES = {
    'DuskceIII': '“Dusk” ce.III',
    'ShturmovayaVintovkaBookerModel838': 'Штурмовая винтовка Booker Model 838',
    'ShturmovayaVintovkaAalto24': 'Штурмовая винтовка Aalto 24',
    '7.92Mm': '7.92-мм',
    'CataramoII': 'Catara mo.II',
    'KRN886127GastMachineGun': 'KRN886-127 Gast Machine Gun',
    'MaloneMK2': 'Malone MK.2',
    'GranataBomastone': 'Граната Bomastone',
    'OskolochnayaGranataA3Harpa': 'Осколочная граната A3 Harpa',
    'Ferro879': 'Ferro 879',
    'Cascadier873': 'Cascadier 873',
    'AhtiModel2': 'Ahti Model 2',
    '8Mm': '8-мм',
    'CometaT29': 'Cometa T2-9',
    'Khangman757': 'Хангман 757',
    '44Magnum': '.44 Магнум',
    'AvtomaticheskayaVintovkaCatenartIV': 'Автоматическая винтовка Catena rt.IV',
    'AvtomaticheskayaVintovkaSampo77': 'Автоматическая винтовка Sampo 77',
    'VintovkaArgentirII': 'Винтовка Argenti r.II',
    'VoltarIRepeater': 'Volta r.I Repeater',
    'FuscinapiI': 'Fuscina pi.I',
    'Blakerow871': 'Blakerow 871',
    'KRR2790Omen': 'KRR2-790 Omen',
    'ClancyCinderM3': 'Clancy Cinder M3',
    'No2BHawthorne': 'No.2B Hawthorne',
    'No2Loughcaster': 'No.2 Loughcaster',
    'KRR3792Auger': 'KRR3-792 Auger',
    'ClancyRacaM4': 'Clancy-Raca M4',
    '7.62Mm': '7.62-мм',
    'KRF1750Dragonfly': 'KRF1-750 Dragonfly',
    'No4ThePilloryScattergun': 'No.4 The Pillory Scattergun',
    'Drob': 'Дробь',
    'ThePitchGunmcV': '“The Pitch Gun” mc.V',
    'LionclawmcVIII': '“Lionclaw” mc.VIII',
    'PistoletPulemetNo1TheLiar': 'Пистолет-пулемет No.1 “The Liar”',
    'PistoletPulemetFiddlerModel868': 'Пистолет-пулемет Fiddler Model 868',
    '9Mm': '9-мм',
    '228SatterleyHeavyStormRifle': '228 Satterley Heavy Storm Rifle',
    'BookerGreyhoundModel910': 'Booker Greyhound Model 910',
    'DawnVeII': '“Dawn” Ve.II',
    'QuickhatchRtI': '“Quickhatch” Rt.I',
    'TyphonraXII': '“Typhon” ra.XII',
    'ProtivotankovoeRuzheNeville': 'Противотанковое ружье Neville',
    '14.5mm': '14.5mm',
    'VenomcII35': 'Venom c.II 35',
    'Bane45': 'Bane 45',
    'RpgCarnyx': 'РПГ "Carnyx"',
    'BroneboynyyRpg': 'Бронебойный/РПГ',
    'StankovyyBonesawMK3': 'Станковый Bonesaw MK.3',
    'BonesawMK3': 'Bonesaw MK.3',
    'BroneboynyyNavesnoyRpg': 'Бронебойный навесной/РПГ',
    'OgnemetMoltenWindvII': 'Огнемет “Molten Wind” v.II',
    'WillowsBaneModel845': 'Willow’s Bane Model 845',
    'KLG9012LunaireF': 'KLG901-2 Lunaire F',
    'StankovyyFissuragdI': 'Станковый Fissura gd.I',
    'GranataTremolaGpb1': 'Граната Tremola Gpb-1',
    'DymovayaGranataPT815': 'Дымовая граната PT-815',
    'GazovayaGranata': 'Газовая граната',
    'LamentummmIV': 'Lamentum mm.IV',
    'MaloneRatcatcherMK1': 'Malone Ratcatcher MK.1',
    '12.7Mm': '12.7-мм',
    'DaucusisgIII': 'Daucus isg.III',
    '30Mm': '30мм',
    'MinometCremari': 'Миномёт Cremari',
    'ZazhigatelnyyMinometnyySnaryad': 'Зажигательный минометный снаряд',
    'OsvetitelnyyMinometnyySnaryad': 'Осветительный Минометный Снаряд',
    'OskolochnyyMinometnyySnaryad': 'Осколочный минометный снаряд',
    'MinometnyySnaryad': 'Минометный Снаряд',
    'GranataBF5WhiteAshFlask': 'Граната BF5 White Ash Flask',
    'B2VarsiAntiTankGrenade': 'B2 Varsi Anti-Tank Grenade',
    'Ignifist30': 'Ignifist 30',
    'Mammon91b': 'Mammon 91-b',
    'ProtivotankovayaLipkayaBomba': 'Противотанковая липкая бомба',
    'CutlerFoebreaker': 'Cutler Foebreaker',
    'CutlerLauncher4': 'Cutler Launcher 4',
    'Rpg': 'РПГ',
    '95070bZenitnyySnaryad': '950-70b Зенитный снаряд',
    '20Mm': '20мм',
    '94.5Mm': '94.5мм',
    '75Mm': '75-мм',
    'MarkIIRaidbreaker': 'Mark II Raidbreaker',
    'RazrushayushchayaRaketa': 'Разрушающая ракета',
    'Model7Evie': 'Model-7 “Evie”',
    '912ShrikeRounds': '912 Shrike Rounds',
    '4CZazhigatelnayaRaketa': '4C-Зажигательная ракета',
    'OgnemetnoeToplivo': 'Огнемётное топливо',
    '150Mm': '150-мм',
    '3CFugasnayaRaketa': '3C-Фугасная ракета',
    'ZenitnyySnaryadAbsol': 'Зенитный снаряд “Absol”',
    '120Mm': '120-мм',
    '300Mm': '300-мм',
    'TorpedaQuillback': 'Торпеда "Quillback"',
    '250mmPurityShell': '250mm “Purity” Shell',
    '250mmFuryShell': '250mm “Fury” Shell',
    'E681BHullbreakerMine': 'E681-B Hullbreaker Mine',
    'NavalBuoy': 'Naval Buoy',
    '68Mm': '68мм',
    '40Mm': '40-мм',
    'SirenaVozdushnoyTrevogi': 'Сирена воздушной тревоги',
    'FlagKolonistov': 'Флаг Колонистов',
    'FlagVardenov': 'Флаг Варденов',
    'KolyuchayaProvoloka': 'Колючая проволока',
    'BuckhornCCQ18': 'Buckhorn CCQ-18',
    'Binokl': 'Бинокль',
    'HydrasWhisper': 'Hydra’s Whisper',
    'KhavokZaryad': 'Хавок Заряд',
    'ToplivoMoltenWindvII': 'Топливо “Molten Wind” v.II',
    'ToplivoDlyaWillowsBane': "Топливо для Willow's Bane",
    'CrowsFootMine': 'Crow’s Foot Mine',
    'NaborDlyaProslushivaniya': 'Набор для прослушивания',
    'FaliasRaidingClub': 'Falias Raiding Club',
    'MetallicheskayaBalka': 'Металлическая балка',
    'RyukzakDesantnika': 'Рюкзак Десантника',
    'Radioryukzak': 'Радиорюкзак',
    'MeshokSPeskom': 'Мешок с песком',
    'DetonatorKhavokZaryada': 'Детонатор Хавок Заряда',
    'AlligatorCharge': 'Alligator Charge',
    'Lopata': 'Лопата',
    'Kuvalda': 'Кувалда',
    'EleosInfantryDagger': 'Eleos Infantry Dagger',
    'AbismeAT99Mine': 'Abisme AT-99 Mine',
    'Trenoga': 'Тренога',
    'E680SRudderLock': 'E680-S Rudder Lock',
    'Vetroukazatel': 'Ветроуказатель',
    'Molotok': 'Молоток',
    'GaechnyyKlyuch': 'Гаечный ключ',
    'VedroDlyaVody': 'Ведро для воды',
    'Voda': 'Вода',
    'Protivogaz': 'Противогаз',
    'FiltrDlyaProtivogaza': 'Фильтр для противогаза',
    'PodstvolnyyGranatomet': 'Подствольный гранатомёт',
    'MaskaPilota': 'Маска пилота',
    'Ratsiya': 'Рация',
    'Binty': 'Бинты',
    'NaborPervoyPomoshchi': 'Набор Первой Помощи',
    'ReanimatsionnyyNabor': 'Реанимационный набор',
    'Plazma': 'Плазма',
    'SoldatskoeSnaryazhenie': 'Солдатское снаряжение',
    'Dizel': 'Дизель',
    'NestabilnyeMaterialy': 'Нестабильные материалы',
    'TeplozashchitnyeEkrany': 'Теплозащитные экраны',
    'ObrabotannyeStroitelnyeMaterialy': 'Обработанные строительные материалы',
    'Stal': 'Сталь',
    'SborochnyeMaterialyI': 'Сборочные материалы I',
    'SborochnyeMaterialyII': 'Сборочные материалы II',
    'SborochnyeMaterialyIII': 'Сборочные материалы III',
    'SborochnyeMaterialyIV': 'Сборочные материалы IV',
    'SborochnyeMaterialyV': 'Сборочные материалы V',
    'RedkieSplavy': 'Редкие сплавы',
    'TyazheloeToplivo': 'Тяжелое топливо',
    'ObogashchennoeToplivo': 'Обогащенное топливо',
    'Neft': 'Нефть',
    'Benzin': 'Бензин',
    'Truba': 'Труба',
    'AlyuminievyySplav': 'Алюминиевый сплав',
    'BazovyeMaterialy': 'Базовые материалы',
    'MednyySplav': 'Медный сплав',
    'Porokh': 'Порох',
    'StroitelnyeMaterialy': 'Строительные материалы',
    'RedkieMaterialy': 'Редкие материалы',
    'Graviy': 'Гравий',
    'TyazhelyyPorokh': 'Тяжёлый порох',
    'ZheleznyySplav': 'Железный сплав',
    'PripasyObsluzhivaniya': 'Припасы Обслуживания',
    'RedkiyMetall': 'Редкий металл',
    'ReliktovyeMaterialy': 'Реликтовые материалы',
    'RafinirovannyeMaterialy': 'Рафинированные материалы',
    'ShinelSpetsialista': 'Шинель специалиста',
    'VelianskiyBronezhilet': 'Велианский бронежилет',
    'StalnayaKirasa': 'Стальная кираса',
    'RyukzakFabri': 'Рюкзак Fabri',
    'SapernoeSnaryazhenie': 'Сапёрное снаряжение',
    'PerevyazGrenadera': 'Перевязь гренадера',
    'MeditsinskayaForma': 'Медицинская форма',
    'KurtkaVracha': 'Куртка врача',
    'RemexGarb': 'Remex Garb',
    'GentlemansPeacoat': 'Gentleman’s Peacoat',
    'NaryadChinovnika': 'Наряд чиновника',
    'OfitserskayaRegaliya': 'Офицерская регалия',
    'FormaOstera': 'Форма Остера',
    'CloudrunnersVesture': 'Cloudrunner’s Vesture',
    'LodesmansLorica': 'Lodesman’s Lorica',
    'OdezhdaAviatora': 'Одежда Авиатора',
    'LegionerskiyDozhdevik': 'Легионерский дождевик',
    'KamuflyazhRazvedchika': 'Камуфляж разведчика',
    'DozornayaMantiya': 'Дозорная мантия',
    'UteplennayaShinel': 'Утеплённая шинель',
    'ParkaCaoivish': 'Парка Caoivish',
    'OdezhdaLegionera': 'Одежда легионера',
    'PekhotnayaUniforma': 'Пехотная униформа',
    'KombinezonTankista': 'Комбинезон танкиста',
    'StegannyyKombinezon': 'Стеганный Комбинезон',
    'KolonialnyyAviadvigatelMalyy': 'Колониальный авиадвигатель (Малый)',
    'VardenskiyAviadvigatelMalyy': 'Варденский авиадвигатель (Малый)',
    'PovrezhdennyyKolonialnyyAviadvigatelMalyy': 'Повреждённый Колониальный авиадвигатель (Малый)',
    'PovrezhdennyyAviatsionnyyDvigatelVardenovMalyy': 'Повреждённый авиационный двигатель Варденов (малый)',
    'AviatsionnyeDetaliKolonistovMalye': 'Авиационные детали Колонистов (Малые)',
    'AviatsionnyeDetaliVardenovMalye': 'Авиационные детали Варденов (Малые)',
    'PovrezhdennyeAviatsionnyeDetaliKolonistovMalye': 'Повреждённые авиационные детали Колонистов (Малые)',
    'PovrezhdennyeAviatsionnyeDetaliVardenovMalye': 'Повреждённые авиационные детали Варденов (Малые)',
    'SkorayaPomoshchR12Salus': 'Скорая помощь R-12 - “Salus”',
    'PozharnyyAvtomobilR12bSalva': 'Пожарный автомобиль R-12b - “Salva”',
    'DunneDousingEngine3r': 'Dunne Dousing Engine 3r',
    'DunneResponder3e': 'Dunne Responder 3e',
    'OBrienV101Freeman': 'O’Brien V.101 Freeman',
    'OBrienv200Squire': 'O’Brien v.200 Squire',
    'OBrienV190Knave': 'O’Brien V.190 Knave',
    'OBrienV113Gravekeeper': 'O’Brien V.113 Gravekeeper',
    'T3Xiphos': 'T3 “Xiphos”',
    'OBrienV130WildJack': 'O’Brien V.130 Wild Jack',
    'OBrienV121Highlander': 'O’Brien V.121 Highlander',
    'T5Percutio': 'T5 “Percutio”',
    'T8Gemini': 'T8 “Gemini”',
    'OBrienV110': 'O’Brien V.110',
    'BMSAquatipper': 'BMS - Aquatipper',
    'R15Chariot': 'R-15 - “Chariot”',
    'DunneCaravaner2f': 'Dunne Caravaner 2f',
    'BMSUniversalAssemblyRig': 'BMS - Universal Assembly Rig',
    'BMSFabricator': 'BMS - Fabricator',
    'MobilnyyAvtokranBms2Klassa': 'Мобильный автокран БМС 2 класса',
    'NobleFirebrandMkXVII': 'Noble Firebrand Mk. XVII',
    'NobleWidowMKXIV': 'Noble Widow MK. XIV',
    'GA6Cestus': 'GA6 “Cestus”',
    'DuncansCoin14.5mm': 'Duncan’s Coin 14.5mm',
    'AA2BatteringRam': 'AA-2 “Battering Ram”',
    'BalfourRampart68Mm': 'Balfour Rampart 68-мм',
    'CollinsOrudie68Mm': 'Collins орудие 68-мм',
    '4045Smelter': '40-45 “Smelter”',
    'BalfourWolfhound40Mm': 'Balfour Wolfhound 40мм',
    'G40Sagittarii': 'G40 “Sagittarii”',
    'Swallowtail9881272': 'Swallowtail 988/127-2',
    'PolevayaPushka30250Tisiphone': 'Полевая пушка 30-250 “Tisiphone”',
    'BalfourFalconer250Mm': 'Balfour Falconer 250-мм',
    'BortovoyGruzovikBMSPackmule': 'Бортовой грузовик BMS - Packmule',
    'BMSIronship': 'BMS - Ironship',
    'DasKrokodilbyVAC': 'Das Krokodil by VAC',
    'TypeBLucian': 'Type B - “Lucian”',
    '81ffRonanBlackguard': '81f-f Ronan Blackguard',
    'TypeCCharon': 'Type C - “Charon”',
    '74b1RonanGunship': '74b-1 Ronan Gunship',
    'HHdPeltast': 'HH-d “Peltast”',
    'HHaJavelin': 'HH-a “Javelin”',
    'HHbHoplite': 'HH-b “Hoplite”',
    'NiskaRyckerMkIXSkycaller': 'Niska-Rycker Mk. IX Skycaller',
    'NiskaMkIIBlinder': 'Niska Mk. II Blinder',
    'NiskaMkIIIScarTwin': 'Niska Mk. III Scar Twin',
    'PolugusenichnyyBronetransporterNiskaMkI': 'Полугусеничный Бронетранспортер Niska Mk. I',
    'BMSScrapHauler': 'BMS - Scrap Hauler',
    'AUA150TaurineRigger': 'AU-A150 Taurine Rigger',
    'CnuteCliffwrest': 'Cnute Cliffwrest',
    'AB8Acheron': 'AB-8 “Acheron”',
    'AB11Doru': 'AB-11 “Doru”',
    'MulloyLPC': 'Mulloy LPC',
    '945gStygianBolt': '945g “Stygian Bolt”',
    'BalfourStockade75Mm': 'Balfour Stockade 75-мм',
    'ArtilleriyskoeOrudie12068Koronides': 'Артиллерийское орудие 120-68 “Koronides”',
    '40250AlektoHeavyCannon': '40-250 “Alekto” Heavy Cannon',
    'Rycker43FWaspNest': 'Rycker 4/3-F Wasp Nest',
    'K81eSombre': 'K-81e “Sombre”',
    '68A4RonanFathomer': '68A-4 Ronan Fathomer',
    'HC2Scorpion': 'HC-2 “Scorpion”',
    'HA1Sagaris': 'HA-1 “Sagaris”',
    'SharkeyDevittBirdeaterMkI': 'Sharkey-Devitt Birdeater Mk. I',
    'DevittCaineMkIVMMR': 'Devitt-Caine Mk. IV MMR',
    'H5Hatchet': 'H-5 “Hatchet”',
    'DevittIronhideMkIV': 'Devitt Ironhide Mk. IV',
    'H19Vulcan': 'H-19 “Vulcan”',
    'H8Kranesca': 'H-8 “Kranesca”',
    'H10Pelekys': 'H-10 “Pelekys”',
    'DevittMkIII': 'Devitt Mk. III',
    'Strider': 'Strider',
    'RinnspeirOrnitierClassGunship': 'Rinnspeir Ornitier-Class Gunship',
    '86KaBardiche': '86K-a “Bardiche”',
    'GallagherThornfallMkVI': 'Gallagher Thornfall Mk. VI',
    'GallagherHighwaymanMkIII': 'Gallagher Highwayman Mk. III',
    'GallagherOutlawMkII': 'Gallagher Outlaw Mk. II',
    '86KcRanseur': '86K-c “Ranseur”',
    'GallagherBrigandMkI': 'Gallagher Brigand Mk. I',
    '90TvNemesis': '90T-v “Nemesis”',
    'SilverhandLordscarMkX': 'Silverhand Lordscar - Mk. X',
    '85KbFalchion': '85K-b “Falchion”',
    '85VgTalos': '85V-g “Talos”',
    '85KaSpatha': '85K-a “Spatha”',
    'SilverhandChieftainMkVI': 'Silverhand Chieftain - Mk. VI',
    'SilverhandMkIV': 'Silverhand - Mk. IV',
    'BellweatherbyVAC': 'Bellweather by VAC',
    'HC7Ballista': 'HC-7 “Ballista”',
    '03MMCaster': '03MM “Caster”',
    '00MSStinger': '00MS “Stinger”',
    'KivelaPowerWheel801': 'Kivela Power Wheel 80-1',
    'KingJesterMkI1': 'King Jester Mk. I-1',
    'KingGallantMkII': 'King Gallant Mk. II',
    'KingSpireMkI': 'King Spire Mk. I',
    'UV05aArgonaut': 'UV-05a “Argonaut”',
    'UV24Icarus': 'UV-24 “Icarus”',
    'DrummondSpitfire100d': 'Drummond Spitfire 100d',
    'UV5cOdyssey': 'UV-5c “Odyssey”',
    'DrummondLoscann55c': 'Drummond Loscann 55c',
    'Drummond100a': 'Drummond 100a',
    'T12ActaeonTankette': 'T12 “Actaeon” Tankette',
    'TanketkaT14Vesta': 'Танкетка T14 “Vesta”',
    'ReaktivnyyMinometT13Deioneus': 'Реактивный миномет T13 “Deioneus”',
    'TanketkaT20Ixion': 'Танкетка T20 “Ixion”',
    'RoosterLamploader': 'Rooster - Lamploader',
    'RoosterTumblebox': 'Rooster - Tumblebox',
    'RoosterJunkwagon': 'Rooster - Junkwagon',
    'R1Hauler': 'R-1 Hauler',
    'DunneLeatherback2a': 'Dunne Leatherback 2a',
    'TankerRR3Stolon': 'Танкер RR-3 “Stolon”',
    'DunneFuelrunner2d': 'Dunne Fuelrunner 2d',
    'R5bSisyphusHauler': 'R-5b “Sisyphus” Hauler',
    'DunneLandrunner12c': 'Dunne Landrunner 12c',
    'R17RetiariusSkirmisher': 'R-17 “Retiarius” Skirmisher',
    'R9SpeartipEscort': 'R-9 “Speartip” Escort',
    'R5AtlasHauler': 'R-5 “Atlas” Hauler',
    'SamosvalDunneLoadlugger3c': 'Самосвал Dunne Loadlugger 3c',
    'DunneTransport': 'Dunne Transport',
    'V1Tzykalia': 'V-1 Tzykalia',
    'TulkaP4Welkinrive': 'Tulka P4 Welkinrive',
    'Mergo4Myrmidon': 'Mergo-4 “Myrmidon”',
    'DaimonaK5Harpy': 'Daimon aK-5 “Harpy”',
    'Toxot902BlindSilver': 'Toxot-902 “Blind Silver”',
    'LuminaryMkIIHarbinger': 'Luminary Mk. II Harbinger',
    'V5bPegasus': 'V-5b Pegasus',
    'RinnspeirMkIZealot': 'Rinnspeir Mk. I Zealot',
    'A59VentiPerdix': 'A59 Venti “Perdix”',
    'LuminaryMkVIEmissary': 'Luminary Mk. VI Emissary',
    'A51VentiDaedalus': 'A51 Venti “Daedalus”',
    'LuminaryMkIVHerald': 'Luminary Mk. IV Herald',
    'M925AustringerManOWar': 'M925 Austringer Man-O-War',
    'TulkaI1.9WhiteRaven': 'Tulka I1.9 White Raven',
    'Betonomeshalka': 'Бетономешалка',
    'StroitelnoeOborudovanie': 'Строительное оборудование',
    'DAE5bZeal': 'DAE 5b “Zeal”',
    'LearyAA70Bolas': 'Leary AA-70 Bolas',
    'HuberStarbreaker94.5Mm': 'Huber Starbreaker 94.5мм',
    'LearyShellbore68Mm': 'Leary Shellbore 68-мм',
    'DAE2a1Ruptura': 'DAE 2a-1 “Ruptura”',
    '50500ThunderboltCannon': '50-500 “Thunderbolt” Cannon',
    'HuberExalt150mm': 'Huber Exalt 150mm',
    'DAE1o3Polybolos': 'DAE 1o-3 “Polybolos”',
    'DAE1b2Serra': 'DAE 1b-2 “Serra”',
    'LearySnareTrap20': 'Leary Snare Trap 20',
    'HuberLariat120Mm': 'Huber Lariat 120мм',
    'DAE3b2HadesNet': 'DAE 3b-2 “Hades’ Net”',
    'StroitelnyeDetali': 'Строительные детали',
    'DetaliPodzemnoyKreposti': 'Детали Подземной крепости',
    'RazvedyvatelnyyTsentr': 'Разведывательный Центр',
    'SC3AerialInterceptorArrayParts': 'SC-3 Aerial Interceptor Array Parts',
    'DetaliShturmovogoOrudiya': 'Детали Штурмового Орудия',
    'YashchikSSooruzheniyami': 'Ящик с сооружениями',
    'DetaliPogodnoyStantsii': 'Детали погодной станции',
    'ZhidkostnyyKonteyner': 'Жидкостный контейнер',
    'PoddonDlyaMaterialov': 'Поддон для материалов',
    'KonteynerDlyaResursov': 'Контейнер для ресурсов',
    'A0E9RaketnyyUskoritel': 'A0E-9 Ракетный Ускоритель',
    'KorpusRaketyA0E9': 'Корпус ракеты A0E-9',
    'A0E9RaketnayaBoegolovka': 'A0E-9 Ракетная боеголовка',
    'KorabelnyySegmentKorpusa': 'Корабельный сегмент корпуса',
    'KorabelnayaObshivkaKorpusa': 'Корабельная обшивка корпуса',
    'KomponentyMorskikhTurbin': 'Компоненты морских турбин',
    'GruzovoyKonteyner': 'Грузовой контейнер',


    # === Добавлено из vehicle_names.txt (авторитетный каталог техники, 001-117) ===
    # Названия взяты из текстового файла как есть (апострофы, '/', десятичные
    # точки сохранены). Коды сгенерированы по тому же правилу, что и выше.
    'Barge': 'Barge',
    'Caravaner': 'Caravaner',
    'Flatbed': 'Flatbed',
    'Freighter': 'Freighter',
    'Krokodil': 'Krokodil',
    'Blackguard250Fury': 'Blackguard 250 Fury',
    'Acheron': 'Acheron',
    'Fathomer20': 'Fathomer 20',
    'OrnitierRPG30x2': 'Ornitier RPG 30x2',
    'Lamploader': 'Lamploader',
    'Junkwagon': 'Junkwagon',
    'Fuelrunner': 'Fuelrunner',
    'Loadlugger': 'Loadlugger',
    'Dunne': 'Dunne',
    'Salus': 'Salus',
    'Salva': 'Salva',
    'Dousing': 'Dousing',
    'Responder': 'Responder',
    'Freeman40': 'Freeman 40',
    'Squire3CHE': 'Squire 3CHE',
    'Knave': 'Knave',
    'GravekeeperARC': 'Gravekeeper ARC',
    'Xiphos7.92': 'Xiphos 7.92',
    'WildJack': 'Wild Jack',
    'Highlander7.92': 'Highlander 7.92',
    'Percutio14.5': 'Percutio 14.5',
    'Gemini': 'Gemini',
    'OBrien7.92': 'O\'Brien 7.92',
    'Chariot': 'Chariot',
    'CV': 'CV',
    'Fabricator': 'Fabricator',
    'Crane': 'Crane',
    'Firebrand68': 'Firebrand 68',
    'Noble68': 'Noble 68',
    'Cestus': 'Cestus',
    'Duncan14.5': 'Duncan 14.5',
    'BatteringRam68': 'Battering Ram 68',
    'Rampart68': 'Rampart 68',
    'Collins68': 'Collins 68',
    'Smelter40': 'Smelter 40',
    'Wolfhound40': 'Wolfhound 40',
    'Sagittarii12.7': 'Sagittarii 12.7',
    'Swallowtail12.7': 'Swallowtail 12.7',
    'Tisiphone250Purity': 'Tisiphone 250 Purity',
    'Falconer250': 'Falconer 250',
    'LucianSM': 'Lucian SM',
    'Charon': 'Charon',
    'RonanMortar': 'Ronan Mortar',
    'PeltastMortar': 'Peltast Mortar',
    'Javelin': 'Javelin',
    'Hoplite': 'Hoplite',
    'Skycaller4CFire': 'Skycaller 4C Fire',
    'Blinder68': 'Blinder 68',
    'ScarTwin7.92': 'Scar Twin 7.92',
    'GunMotorCarriage': 'Gun Motor Carriage',
    'Harvester': 'Harvester',
    'Taurine': 'Taurine',
    'Cliffwrest': 'Cliffwrest',
    'Doru12.7': 'Doru 12.7',
    'Mulloy': 'Mulloy',
    'StygianBolt94.5': 'Stygian Bolt 94.5',
    'Stockade75': 'Stockade 75',
    'Koronides120': 'Koronides 120',
    'Alekto250Fury': 'Alekto 250 Fury',
    'Rycker4CFire': 'Rycker 4C Fire',
    'Sombre20': 'Sombre 20',
    'Scorpion12.7': 'Scorpion 12.7',
    'CaineMortar': 'Caine Mortar',
    'Hatchet40': 'Hatchet 40',
    'Ironhide40': 'Ironhide 40',
    'Vulcan': 'Vulcan',
    'Kranesca40': 'Kranesca 40',
    'Pelekys68': 'Pelekys 68',
    'Devitt40': 'Devitt 40',
    'Strider3012.7x2': 'Strider 30/12.7x2',
    'Bardiche6812.7': 'Bardiche 68/12.7',
    'Thornfall7.92ARC': 'Thornfall 7.92 ARC',
    'Highwayman14.512.7': 'Highwayman 14.5/12.7',
    'Outlaw407.92': 'Outlaw 40/7.92',
    'RanseurRPG12.7': 'Ranseur RPG/12.7',
    'Brigand307.92': 'Brigand 30/7.92',
    'Nemesis68': 'Nemesis 68',
    'Lordscar94.5': 'Lordscar 94.5',
    'Falchion40': 'Falchion 40',
    'Talos75': 'Talos 75',
    'Spatha40': 'Spatha 40',
    'Chieftain25012.7': 'Chieftain 250/12.7',
    'Silverhand6840': 'Silverhand 68/40',
    'Bellweather12.7': 'Bellweather 12.7',
    'Ballista250': 'Ballista 250',
    'Caster': 'Caster',
    'Stinger7.92': 'Stinger 7.92',
    'Kivela': 'Kivela',
    'JesterSM': 'Jester SM',
    'Gallant': 'Gallant',
    'Spire': 'Spire',
    'ArgonautRPG': 'Argonaut RPG',
    'IcarusRPG': 'Icarus RPG',
    'Spitfire7.92': 'Spitfire 7.92',
    'Odyssey': 'Odyssey',
    'Loscann': 'Loscann',
    'Drummond': 'Drummond',
    'Actaeon12.7': 'Actaeon 12.7',
    'Vesta': 'Vesta',
    'Deioneus4CFire': 'Deioneus 4C Fire',
    'Ixion30': 'Ixion 30',
    'Tumblebox': 'Tumblebox',
    'Hauler': 'Hauler',
    'Leatherback': 'Leatherback',
    'Stolon': 'Stolon',
    'Sisyphus': 'Sisyphus',
    'Landrunner': 'Landrunner',
    'Retiarius3CHE': 'Retiarius 3CHE',
    'Speartip7.92': 'Speartip 7.92',
    'Atlas': 'Atlas',
}
